apiVersion: v1
kind: Secret
metadata:
  name: stirling-pdf
type: Opaque
stringData:
  #ENC[AES256_GCM,data:7AEYYraNzuz0jQqeoNG1We3GHlS5Lkrq,iv:YD0gGGjJnRqov+TqxelsxdyDP0OuTqrphKCZZahT6QQ=,tag:d+jRZIpQSBx7Sd/JzTUKMg==,type:comment]
  SYSTEM_DATASOURCE_ENABLECUSTOMDATABASE: ENC[AES256_GCM,data:o5rDWt4=,iv:ouZD1JpvcK8Ft6Hx+e3ybKIQsfpgEyaSCj6Ot+sa08E=,tag:Au1KdmS0Hmwuvf70u6UV0w==,type:str]
  SYSTEM_DATASOURCE_USERNAME: ENC[AES256_GCM,data:d7ZQUfMCKRw=,iv:JNBd5a60dv2yvHKmbteRhpn/FWu9YN6Zgq2pIy201+Q=,tag:sAF2V2cU6RiALiaG/0qTkQ==,type:str]
  SYSTEM_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:mCAuw1SeOb08Pbut25rQ0dG7+fEimcsUyTUduvwUD3fBX5NutRiXyoaA+RT0U0Qi1vBJGcmjMxgHsRgZIy4Hng==,iv:3xHyQsaWos2hSPytUKEoK9Gd1FAhvKJdNfOVosBfzDU=,tag:XetjwxA0QYJ1Dk6PagLdew==,type:str]
  #ENC[AES256_GCM,data:cJ3ZeQHfNAuvgedEmD0=,iv:Meks5Ox99bowuZBoA4u+4Yc2XD8Fa1MjkRgPIpbPz10=,tag:+NulueIod+9pJy+sLEMweQ==,type:comment]
  SECURITY_ENABLE_LOGIN: ENC[AES256_GCM,data:JGLQPQ==,iv:xsL+7lIn+QrT8avk/QmcNbE43SGzGHK1zrlbVcJCH/c=,tag:kP9hvqDqJeo9oh1goH+Hug==,type:str]
  SECURITY_LOGINMETHOD: ENC[AES256_GCM,data:PKkBL/H8,iv:yHoX/n4m2PBzoFs+XqP3REByRynCwVXiF/GzAdcHByQ=,tag:qqH35rcQfIwhbjmp1sNTLQ==,type:str]
  SECURITY_OAUTH2_ENABLED: ENC[AES256_GCM,data:0kerkA==,iv:nonRlX7OfsPRrCx5Qp9HLzI4khFVxLwCTXPjWMsFwLc=,tag:rsChFWVRbjPIIF0OZKr7gg==,type:str]
  SECURITY_OAUTH2_AUTOCREATEUSER: ENC[AES256_GCM,data:j1nXqw==,iv:r/du9HzLQz79adKm1HZOjBORITHjCiaaOhkcx9rMGiY=,tag:jB1NyUSqYNpCCkB1Kn+ijA==,type:str]
  SECURITY_OAUTH2_ISSUER: ENC[AES256_GCM,data:WsZ25nwXnuqKNeBFqW01C7Q6OkxU7bN5ulcVI7QSbcjUETveabuB0WFfY4ijyETNBQ==,iv:klSIrKz55/j0ffradjl4kehJk9fcaEF/WY6lC1x+6uY=,tag:ty5ravnMc8bYsg7YqCVXKQ==,type:str]
  SECURITY_OAUTH2_CLIENTID: ENC[AES256_GCM,data:rT99tiutou9KhDbjvfQhnD9L6oPoFYVJSPixaWTwLdVjFzz4lgDt+w==,iv:EzJiQWK7BcpkiRuqZYjeM3aKwn0kBUBKHQeYAyHfZco=,tag:ANCm9e/f5qJFMjGBnJnzmA==,type:str]
  SECURITY_OAUTH2_CLIENTSECRET: ENC[AES256_GCM,data:oYFN4WOpE/0ZtbTyTkN66Cpsqo6J3yg5cgBy/+WIDqNWLV3oi2Pg4EAWl6cNR436tfFp1m1Udy8KwzJ2PXDNn5Sw86ORFZxlTByEydUt8FtSal/4O1AviHbgFgj3gRGNcCChi7KsTRYreA1+QZaUzIIUne+LiCY9rOwnBCcFHLg=,iv:2o/LZ/NUUza+cjL/xEtRZJKUseyZCQbtqbVQJZuF/tc=,tag:6/PuaL3uhcMViBuwrABj9A==,type:str]
  SECURITY_OAUTH2_BLOCKREGISTRATION: ENC[AES256_GCM,data:2nN7WiI=,iv:nndEhZeYpvbiCx9AQHJgTv66pJ5kk6EKiZnXJvurNxY=,tag:XsiExt0ZNOc8lYyr0gTSaw==,type:str]
  SECURITY_OAUTH2_SCOPES: ENC[AES256_GCM,data:vwBC29vfXt0DdoVmvyGZKqGKel327Q==,iv:fC/vEKGVQhK6R84i0GDG17oMtH/ijOc0QlyXummlRt8=,tag:pv3NRAsse5T9zpOoSRjTkA==,type:str]
  SECURITY_OAUTH2_USEASUSERNAME: ENC[AES256_GCM,data:Cn5mS78=,iv:FCPCKyEDeH98A1z1yMTiLZDaeTqqezwam0/OXQ3bLOI=,tag:DImgADc98rNSQ37zqzPwVQ==,type:str]
  SECURITY_OAUTH2_PROVIDER: ENC[AES256_GCM,data:GKYfga0B3bQ5,iv:xwI/fCj1oY9UpJ7kcO/XGZDaen8EPMOILKG2YFBCTfw=,tag:CSEh7tdvvmvYBZ6SNI3P5Q==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMHpOc2JYUDJsZDZ3SEp1
        QnQ1ZjE5eVhjRjJwRVZBaEZIOFMwZUJkTEU4Cjk4UlZPT2M5NU9QS3IwTWt1RHVG
        MlM3eEEwRFg2bkpWc2NFdDFKNWh2bEUKLS0tIEdDZWlaYmVycnpKTVFqQTBmN1ZD
        S21JaU4rUUFRdUhFQ1FHV2dBSXQ2d28KYOvBEx0R/W4Wk7IcbI7ElbnSYuQnft4w
        2jjTqJwpbO97HqHFz2HmvCeNcjpRXxBwUb8zUa/8u7GdnUwJO3ihCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T15:12:09Z"
  mac: ENC[AES256_GCM,data:DZBKpqdxRfuZc8gvPhUFga+YixB9AgQtYfHPK+mLqNDU8DZzzDtfK0CFq15a6ERtXlazZe9BZyb07V5cUjJlSmfu8caf/caSWRTaxlr507k6a0Ks0kNOXLL1VpMxn5+QGz0bPpppnCXM1CqjT9Zmb3WPxsq95x/aAN7w77mX2/E=,iv:z2HBt8EdRVUjM+JoI9I4GMCF5EoX2kNLHv3lObvmwFI=,tag:gLBNF8Wqq2ftmVoIuprD2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
