apiVersion: v1
kind: Secret
metadata:
  name: stirling-pdf
type: Opaque
stringData:
  #ENC[AES256_GCM,data:7AEYYraNzuz0jQqeoNG1We3GHlS5Lkrq,iv:YD0gGGjJnRqov+TqxelsxdyDP0OuTqrphKCZZahT6QQ=,tag:d+jRZIpQSBx7Sd/JzTUKMg==,type:comment]
  SYSTEM_DATASOURCE_ENABLECUSTOMDATABASE: ENC[AES256_GCM,data:o5rDWt4=,iv:ouZD1JpvcK8Ft6Hx+e3ybKIQsfpgEyaSCj6Ot+sa08E=,tag:Au1KdmS0Hmwuvf70u6UV0w==,type:str]
  SYSTEM_DATASOURCE_USERNAME: ENC[AES256_GCM,data:d7ZQUfMCKRw=,iv:JNBd5a60dv2yvHKmbteRhpn/FWu9YN6Zgq2pIy201+Q=,tag:sAF2V2cU6RiALiaG/0qTkQ==,type:str]
  SYSTEM_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:mCAuw1SeOb08Pbut25rQ0dG7+fEimcsUyTUduvwUD3fBX5NutRiXyoaA+RT0U0Qi1vBJGcmjMxgHsRgZIy4Hng==,iv:3xHyQsaWos2hSPytUKEoK9Gd1FAhvKJdNfOVosBfzDU=,tag:XetjwxA0QYJ1Dk6PagLdew==,type:str]
  #ENC[AES256_GCM,data:cJ3ZeQHfNAuvgedEmD0=,iv:Meks5Ox99bowuZBoA4u+4Yc2XD8Fa1MjkRgPIpbPz10=,tag:+NulueIod+9pJy+sLEMweQ==,type:comment]
  SECURITY_ENABLELOGIN: ENC[AES256_GCM,data:Xs6PDw==,iv:8epby8m0PbPbuUvMwm9B53e46FuFfHLoHGLJ98awcls=,tag:STckcPYUJxxYR7PyUz0kCg==,type:str]
  #ENC[AES256_GCM,data:KVxpMdNejtM82jvi5kgUMiBte+58oaAv/07kaESQ,iv:SZgqLOOnTP/Frw8KuS1H4xKbeBAFWH4NeH8bSgMOkxI=,tag:+LWNDV2rU61jTaU4F58mDA==,type:comment]
  SECURITY_OAUTH2_ENABLED: ENC[AES256_GCM,data:0kerkA==,iv:nonRlX7OfsPRrCx5Qp9HLzI4khFVxLwCTXPjWMsFwLc=,tag:rsChFWVRbjPIIF0OZKr7gg==,type:str]
  SECURITY_OAUTH2_AUTOCREATEUSER: ENC[AES256_GCM,data:j1nXqw==,iv:r/du9HzLQz79adKm1HZOjBORITHjCiaaOhkcx9rMGiY=,tag:jB1NyUSqYNpCCkB1Kn+ijA==,type:str]
  SECURITY_OAUTH2_ISSUER: ENC[AES256_GCM,data:/4bzWAX5ZS8/o8yXv+LHmgm3KkkGzAQ0+0k83jXzQtntlokCFD50yMOSbPQK22uBRrk=,iv:HBR4rO8hOg4TFalScrdOkoUKs1jNcGw/LHTi27tK/dc=,tag:uxwXYx8RxJzRUZZnkl6BCg==,type:str]
  SECURITY_OAUTH2_CLIENTID: ENC[AES256_GCM,data:x6zJqF/O8nBR17UiLqBwGkiNud23bICupTo995wOFBoBKM/fKYQ6zw==,iv:vYTxRJyM14MZQQT1zW7t5bXB3Y6THhn/Ra/OFhJMtIc=,tag:PVJgKrDx+GmRMZrfd70CbQ==,type:str]
  SECURITY_OAUTH2_CLIENTSECRET: ENC[AES256_GCM,data:QXdjI9vyj6hmbbIOAi0BYrFoiVr7ovDwd0orKrE3bBsQ19hsmHEVOjLhW7uF3p5KoHeA8j2+O0CiL/VKM19QRpM97pb6/Zfz2IUS1gBuUt8td0+U5mtJRKlvdZHVoUePgTdNbgOyTyBBfiXLUQgzeGjFm1reLgc0iFc5OzDkCe0=,iv:VHm7nYfldhjJZ3JVNVSbBP3shsuIdGJaAPJfIwLlSck=,tag:b+gVRYVRFqYjROtiOXrvgA==,type:str]
  SECURITY_OAUTH2_BLOCKREGISTRATION: ENC[AES256_GCM,data:2nN7WiI=,iv:nndEhZeYpvbiCx9AQHJgTv66pJ5kk6EKiZnXJvurNxY=,tag:XsiExt0ZNOc8lYyr0gTSaw==,type:str]
  SECURITY_OAUTH2_SCOPES: ENC[AES256_GCM,data:P6PQxVvElor70XDLMnw6fVItGDlWn6qo,iv:YlqFSYVP1gBaTiAdOn1B3XfjBrpax8afUb3Bh3ehdrE=,tag:H7B09ZcVuZ0/iQ5zmTq7/w==,type:str]
  SECURITY_OAUTH2_USEASUSERNAME: ENC[AES256_GCM,data:Cn5mS78=,iv:FCPCKyEDeH98A1z1yMTiLZDaeTqqezwam0/OXQ3bLOI=,tag:DImgADc98rNSQ37zqzPwVQ==,type:str]
  SECURITY_OAUTH2_PROVIDER: ENC[AES256_GCM,data:GKYfga0B3bQ5,iv:xwI/fCj1oY9UpJ7kcO/XGZDaen8EPMOILKG2YFBCTfw=,tag:CSEh7tdvvmvYBZ6SNI3P5Q==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMHpOc2JYUDJsZDZ3SEp1
        QnQ1ZjE5eVhjRjJwRVZBaEZIOFMwZUJkTEU4Cjk4UlZPT2M5NU9QS3IwTWt1RHVG
        MlM3eEEwRFg2bkpWc2NFdDFKNWh2bEUKLS0tIEdDZWlaYmVycnpKTVFqQTBmN1ZD
        S21JaU4rUUFRdUhFQ1FHV2dBSXQ2d28KYOvBEx0R/W4Wk7IcbI7ElbnSYuQnft4w
        2jjTqJwpbO97HqHFz2HmvCeNcjpRXxBwUb8zUa/8u7GdnUwJO3ihCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T20:02:07Z"
  mac: ENC[AES256_GCM,data:Jho+IqyKzRdVGv9tFgS75HtOS+Ijak1QeXZrjEH1WQV5dqCb9LL9mBxUZmpzLWuV3kuB+gUX/C6EnhxeT4tcPYznqFm5+99ltPqYpzUFUK1waIy5ntMGx1kn+EATp87fJrtfEf6UK/p//eMKWvma/QHhS+UrY/nosL4F45Z6tuU=,iv:tyb7Y2eqdtAepdAlH8iLp5yUJRfRhBZbCWhT14ttZX8=,tag:44lKiZVuR01qWUVhwPXULQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
