---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.mariadb.com/database_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: riva
spec:
  mariaDbRef:
    name: mariadb-cluster
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
  requeueInterval: 30s
  retryInterval: 5s