---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.mariadb.com/grant_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: riva
spec:
  mariaDbRef:
    name: mariadb-cluster
  privileges:
    - ALL PRIVILEGES
  database: riva
  table: "*"
  username: riva
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
