apiVersion: v1
kind: Secret
metadata:
  name: riva-db-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:3OqMInbQUtAilwPc19H7aD+/3GxDYqx7Fnaztno/n1EAKdfTQOsnjeuywNfNU2Ct+8twMuUkOqj6Vft4AhOviQ==,iv:ck1efuRLt7JYLJeJYG9K9hBuBq+GC4loNoWqAW8t9LU=,tag:YL1j1dFYrAlh+p35IPlvwQ==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T20:54:04Z"
  mac: ENC[AES256_GCM,data:9n/TaEn5ZUGo/s4++gn172Bn5weGUFToLTaV0SBCFH9U7N8K31TEOhnvQ1U+9m2Cq21hbkE2lJH40kBWODxcFG8Z081CUoQTM6clelXhjQKQWCFmaTxcit7jaMYuMsf7AnIfCp4LSkvvD33RmG+2HK0yLtX5yB13TSel/KPoRFo=,iv:ei2fbjC5cE0zUs7R9piU0Cn97YoTTyf9GNv6kyB38Zk=,tag:Rb7qqJA3JtdGQf98bDW/Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
