---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.mariadb.com/user_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: riva
spec:
  mariaDbRef:
    name: mariadb-cluster
  passwordSecretKeyRef:
    name: riva-db-secret
    key: password
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
