---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  quote: '"' # double quote var to support substitution as quote
  # Cluster IP's (Cilium range [10.0.2.0/23])
  CLUSTER_INTERNAL_ROUTE_IP: 10.0.2.101
  CLUSTER_EXTERNAL_ROUTE_IP: 10.0.2.102
  CLUSTER_BLOCKY_IP: 10.0.2.121
  CLUSTER_MOSQUITTO_IP: 10.0.2.122
  CLUSTER_HOME_ASSISTANT_IP: 10.0.2.123
  CLUSTER_JELLYFIN_IP: 10.0.2.124
  CLUSTER_QBITTORRENT_IP: 10.0.2.125
  CLUSTER_SOULSEEK_IP: 10.0.2.126
  # External Services
  LAN_CLOUD_KEY_IP: 192.168.0.2
  LAN_NEXTCLOUD_IP: 192.168.2.216
  LAN_TRUENAS_IP: 192.168.2.210
  LAN_VOLUMIO: 192.168.5.3
  LAN_NETKEEPER_IP: 192.168.5.1
  LAN_PRINTER_IP: 192.168.5.4
  LAN_ZIGBEE_ADAPTER_IP: 10.0.2.123
  # Redis DB id's
  REDIS_IMMICH_DB: "1"
  REDIS_BLOCKY_DB: "2"
  REDIS_INVOICE_NINJA_DB: "4"
  REDIS_NEXTCLOUD_DB: "5"
  # Service URLs
  POSTGRES_HOST: "production-rw.database.svc.cluster.local"
  POSTGRES_PORT: "5432"
  DRAGONFLY_HOST: "dragonfly.database.svc.cluster.local"

