apiVersion: v1
kind: Secret
metadata:
  name: grafana-env
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:1W/eiw==,iv:3e1bUyGKpj4pEPVioiEm7lPnVByz0AdTKBU/aeTtuIw=,tag:WGvhAS9gmMWEzaYfvF4mdw==,type:str]
  GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:euEvK6JWAGwYug==,iv:2H9dnc1YujIz3w/9bmLIIiAJeg7o/qo7sedSUuKpl8g=,tag:rhu8NwWgC/TcUBl45pB2QQ==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:JdRp+zfSMv5RqVB0bgij4CwuO0SW/XAjZeJudLiy0b8L5ile4YStew==,iv:MtuPuYhOA11X59BRYFjV/972nfO3ArEvOC43FsnwgSk=,tag:hOZgXlTsPsKuwPv+oqgpRQ==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XlhKrAKx1i5LCzbefKZWDi+BPS4TfhWF3IP0xvQ3PBw9MPHRXHKMkl55kEYPe6CnPGFWcCZtOzqyOafCv2LqTrbiIAOMyyqC0rJhnNtllcDmMDZQ13vQFUPguj3ahDQE/yuG8BVEC/p+1x7gYqdLwT4+JLmFgiY8qznH/dPMUjE=,iv:3XUIbd6m9ycB+wtRpPrxBr3k/lzgI8WJdCi51lj+V+Q=,tag:8TiruBMWzYBj2d7dxCraIg==,type:str]
  GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:xY/nrY/Xxnn+kFFgFcC9RbhEmWg=,iv:OWOZ/EWOoofK3muPN/64Y4zwuV2k21xWr46MDELwgj0=,tag:anM3zjymP5sUQGfh/b7Exg==,type:str]
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:xZOKzATp289irGHJU0N2qD7kICUdQYJTHi30MZJctVSEmd8wnD5KPWlFYwpqcUA=,iv:73SVARNpedQodWwGd8A+Hl0jIdHwZ2RWoq8VjKKDebA=,tag:dCVK25krSglux4RI0ejSDw==,type:str]
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:aYHkVu7Y6CpGRjgwA3irdeMEEOw7gEHETpvp/M5KsBvoHQ7JmtMZ+yfllq6AZDyB2r+HPS8=,iv:POMcGnO3NiF1GctWR2KJIagTr2zS3ELdDs46vvvEAgc=,tag:eZapDHpeKmKxdzhS0Bqxnw==,type:str]
  GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:Y7jvw87BVOJQH8iKXbcQyIEdNUvRrx2sWoONp/qHcecL02lnAEnlHRpF78LCTXQXHDTNU8anTLU=,iv:GJ1cVGDprZqW0QkATwnzwg92phAzXaVF1pgncgxtHTM=,tag:qL4box2VqWcMYUKYiuhq7g==,type:str]
  GF_AUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:gmmUSFNcjSnHuDDIBSGHzdUEg9jkkcmXLLcKDoBsRz9qhPiMRRRuBR1gCGSTeBZSK5PpAT/YjgVR,iv:wBOIFcgQx81AlSPXXhBSZr37z7mTZcDnO9B1ioOru9I=,tag:G1XRMZLAPMxU9DiYFAFS/g==,type:str]
  #ENC[AES256_GCM,data:VvFOcDoQ/bbivZDbxd5lyIco0YJ6kFVzN3byIpjJTOOTqL7TwgAWTU31XwuihYN3QzM0vJ1fDETfwUnDog==,iv:UdM9RLfUb22xVlju/AImxITFOvCMj3EoHoTgnSrb59s=,tag:qZ3ZVOwE6E4uboUbz8Ig8w==,type:comment]
  GF_AUTH_OAUTH_AUTO_LOGIN: ENC[AES256_GCM,data:12wLig==,iv:dxM2ZQhU3zIcO4fvDhQTjs2Zb8zmGsVue+OdpuDj/Xc=,tag:IV/Iio/dUbwM+Ynk+bL18w==,type:str]
  #ENC[AES256_GCM,data:Y26nbuIv5Aggch90qjCWAZWP/5a9l3oZ4bV7Tk2wVHuhpC+p0/s+Ppl9Cys=,iv:3UcbFeK2ELq77E+I7+U2lSP3Yf2yTn2MnNiqI6oJNMM=,tag:5B+OR/rwA119xHWbcn4XTg==,type:comment]
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: ENC[AES256_GCM,data:FkVyLYUGmv8HVxhuzH37vPgxkUI0p2JVKt84Vyti9uQtZxhcy0trAIwxjog/yjV1xOUMi1tEVIUGsUTV2IBi5ZHjU3P8o5x861nIDe6sJ+5zb2tmXEpb2ux/r7kP9qU/Z+QmXQYaLHiH96xq,iv:IMMbH/qwxSQJ2SKHmB/JuhFCr0uDZRLL4c+yc/aaiho=,tag:jQeWgEUq6oizrjQvVwKK5w==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdjRMMzBaZXdOamMva2t2
        VzgySWd3Ui8wWDlOK0lMU1dMRkZoUlVtRTFVCmNSNjVDcWZ4RVlZVE9ESzJaTHlt
        OWtnRFJ1a2gxZ2UxdjhVcklVNFJvNVUKLS0tIG1DTENRYW5wY1hLUmh6SzBmendV
        MkJUYml2M292ZmpYb3JVNEsyTkw5eFkKJS2sUWoM5D3N/1Oz+kKH2ifVL/QFeEib
        1WilqyXoBwEmVnj9xYdJESeWzMvBklMoTUcJxrjcRQMNgMgrD03MCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T15:42:19Z"
  mac: ENC[AES256_GCM,data:kyDk+zNLgbtrh6C1TrLzV2coLeHJ+QV436WMfLEiOqjuVjYisDmK49plHs1Ia7IdeWeVHVfyJeGeReX4dPY6+ekGpGv1Zy7xkzMH6YilaaEeVHGFMdkW9mjDyrD3+r71W6x14qmQ+kyyTuLyVZ6vvqJId1O+bFxduXcb63I5dBg=,iv:U7r5l/XepSS7bs+7JW4hhFgjDDTWOMay/70G7+3Qgsg=,tag:ddEcW38FSU4igakM8VGrhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
