apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: security
type: Opaque
stringData:
  AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:62yFUNTaabMHmqnTZ9kReQ6TZABXNdS3UywUlkZjTndPTYwHflluFQ==,iv:0n5wIjOASyn6hXyV8AjHTMLz3PyyC0karDEkHJcFIfg=,tag:8OZazLelUBCIcJkFdXmSdw==,type:str]
  AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:8kSvGy7C452k,iv:ZoFfWcE0RiS3DG+dM1Su5XUNkRStusa2Lxkj/TccQbI=,tag:3rMKLPHSMzZuC+JGeBlAyQ==,type:str]
  AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:0Gm2xOZQE1go,iv:BScHCSh/VeYKr9I22Wc8kJtHlFopA7hKTy8Cqd7GMbc=,tag:R4Ze+uZXJEY8rWzpFKhtGw==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:KLP7a+52PrwhLiilOiRAwmd7MHOQTg7GPBjy2jUAoNeFXCR+VU+jaeUofA4T7VQVXxi5FsPDY4Em8bwp3/oEqQ==,iv:c9fUqe0G/SYM+csJkM+5kRH+jQKBjEySMT4X900iUYc=,tag:c7bfwNRw9FbKz0ctRpWnSA==,type:str]
  AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:ZplRf1eBosDbJ/Li+3XJfJQO,iv:wK6HHCpby1UQ4P89BW7i6oEJGBh2rgjFJx8dlERoV6g=,tag:x/2Uec2Tyby5sa1ry6I4ZQ==,type:str]
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:UAOsNNcZx/ohsoSm/hP3KebKmV8e3O6MmIzk7WNTjj/eBABGlYAD2JgdCMm2kH5UkN6relRNyoFblb9LgwU+Xw==,iv:yHk71MtjhifJrBOPVMb/dDcjXIosCJSYA81pmp5HVM8=,tag:PGthal38xuNrYYRykaeENg==,type:str]
  AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:5Oz5fhAsQVArvqxg/sMr3whIi/oDz9I6j6V80/M9VU7ZUyTCZHKgcOSDCxzQu9hGeCNjvVZvZDGxKxqkmohpFg==,iv:Apei82ssPzgdfwNFLfv1hBZGx9lafA407gL86fnL39k=,tag:f9378rI7CCgmUTMqz35ZSQ==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:t8bQtQY110TaWmd3GlIRhXssb0UB9QoTB/zRegXI6hf9v8dWTJJGp9Q0zQ3ELzrU0wZnxsaSHLqjPuFNTz7q6A==,iv:98Jf1/eHTsQoZN3ihz+kd9AtGKpqF3y95CKpLY29MSk=,tag:l96E0d5jW9b74X2RRjCvzg==,type:str]
  AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:jrRIBc4QFJ35o+tDlulZqdxP,iv:DEX9iNGvAjdkqTQmoOv14Cdgtr5gpqt1CMjGEDD9mQQ=,tag:pSt668mwelpT4Zw41dSslw==,type:str]
  AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:Csvp,iv:LnjwQi2khu4Ubx9UCkDtQc8zjoRL9+2zbDWPHQFUJOA=,tag:o0ahVzYBLFrEHODnssBzPA==,type:str]
  AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:ENKbdQVo/oU4Z/Do4IALIrxy,iv:l4wZ6y48jxYozaFqHYDbwbQ15ZekWevlSk6nCp0LXSU=,tag:zboHW7DZ8SnHhwps2rsSsw==,type:str]
  AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:Sv9GNyrko4kNHgMSUDjTmw==,iv:aNdTFPdnEWvujMaQFl2LUC1BnC4XMwVeILuraaiMCMQ=,tag:V+aGzhD7IqyEK5CEh8wJQQ==,type:str]
  AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:iPACRQ==,iv:egJuH6o+IaytiNHzgkSSZ8b9GUFswDhK1xBwURY4u+E=,tag:PkrhNdogGahW11TPxUmd4w==,type:str]
  AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:UKuA6gs=,iv:5t7SL0vOwqwp/Mdeqs+hxodZlO0Fj/RW4KHFSx/tiAs=,tag:jWC2hMH+hCDzykYbL4hnJA==,type:str]
  AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:37sYvrIkqQAelp8bYLRCKY2k,iv:iBq0JBwFEuvGCzUZC4JPXXCxg7SW8En7tasl97SGuqA=,tag:9GkZyiBw9iyzRa2k+i/GJg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZG9mclhOZ2M5aUtlTWV5
        V2tOdVpOdGF3LzlSY0VBN0hGREdzK3RrT3pRCkRPcDJNWThRT0hwMUVxVlZOdEFa
        U0o3UnhBZXhNUE1BamMwMEZGRzBUZ0kKLS0tIGt5d3lCelVMeXB1MHJrek1rd2Fv
        UEZBWkJ5VTNGQW1GcTNLS3N4TWdhQk0KpOOY+8YgefIfXvsW+F4GHNVScuWpmuGX
        bCPs1bUIQQf/f56j9zCGQBY0O7QQwvNj13XCAEPiwZPVbMu9d3IcSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T13:33:59Z"
  mac: ENC[AES256_GCM,data:/VAd/DNaH2/qroF4TR0FnOTf6cvUyOBqMtRmKprQixzP8fjp7Ntt3aiz0jSkZ+kOsYGxcI0eD+InJTEQFm4oz1homO5mGvzpXqy8IGrcv0NvjxGbnlNyh+LT5pv5hnUt0l1Jrv/dYWkPFh1Gksb3lG0VjwavY0zpdVMVwBWh2yo=,iv:jsUrkJt9hLsvnu9slTvN9pMPgBndXU6Yh2vnSrGNcf4=,tag:6nxEoSOQT4Sj6c4kM89mTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
