apiVersion: v1
kind: Secret
metadata:
  name: mariadb-user-secret
type: Opaque
stringData:
  wordpress-password: ENC[AES256_GCM,data:DQLNu8A+iq8ksDtUIGV9r71qZmvrO97EYSGj2Pyawh/yIpm55ZXLWrFFOy/9eqZNivGOAjAImC9x2sQdFM2vnw==,iv:Yf6kfV0s33LvWpMleSPD+PZj1QRw7xvPMUI6RwHkomw=,tag:w3dKxt8JcLGrr9Raty5Ixg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T20:41:50Z"
  mac: ENC[AES256_GCM,data:J7kKC9m9srf80kBL02wC2T1SY1mbEc0U3yc1UxiiERgBhYCxn8rtREMa50gU6rH2FZZQ9wN0FRaoMMFF1z+RXcvZ576KTDKJrUpPQdiSmiC0Wb/WY0vQBHyCqGfixZVRnI/ByF72w0YpDVVpYwM1C0DfuymueGsgUhzy5hBf5zc=,iv:SY1M+JSX8mPYP4BZFlcN3S2k8123vspuZ+wnfqhfHgY=,tag:XRsLtyiDAyhu0cyAZojn7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
