apiVersion: v1
kind: Secret
metadata:
  name: blocky-database-secret
  namespace: flux-system
type: Opaque
stringData:
  BLOCKY_POSTGRESS_PASS: ENC[AES256_GCM,data:WR5LdLgdone7b5NdaI61WcJYwIcqTLvV/hJtlH3Sr5P/3zhP7EtXwjPT8mniIzXpHQ==,iv:HRr9RIYYFV2gmiMKOxhKBmlDamZjA8RsEmR/4TOPlPk=,tag:ILVCeA2KiZNsNaHIwL1eMg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTlp3RHRleUFnTEtYSk55
        NEJlWndib1dHckhnOVdkdDdET3FxMm5ncjFzCkVuby9HNEw3cFNkenVZYVcyL2ov
        ZWZpNVoySWFaeityOUp3TWF4YnQ0L2MKLS0tIGh1RlZuTmI2dS9iMldVcTdoSnFu
        N2pTODMveThmcHkySDJORVVjYmFoUjgKSPezIjHsSzD1q8ASV2OBC/9TEltFVnoS
        8CDaFcziBUzTfHyAbGw8AIlg+6BMmD4+T7ATufGjBYr60nIZtYQ1PQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T14:13:49Z"
  mac: ENC[AES256_GCM,data:L5mWDic8OpGTLj3k8+yrlcEkgXG1024LNNmqEAHtxX5HIHoylqncU9r7a3cfpmPAOJGOA+bEetokJxJHWpkg6KH3we68hEj3jR3duOghUyB6UiqLrA0Z26PJfnRKSg7mskvhalZxhKM6fOjf6Xcj01vtJKAJVu7Y0twzh/8+ji4=,iv:/tblmufPLe/4Ba4xCG0vbV1qw+GVXTKXCNgF/ven0Rs=,tag:Bx1KgTAeTQYYoIiQo6LSDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
