apiVersion: v1
kind: Secret
metadata:
  name: mariadb-cluster-secret
type: Opaque
stringData:
  mariadb-root-password: ENC[AES256_GCM,data:CvGNNyij42bg03wt+Mk1QTQLzMW1QtzNPSIkgNwq20RxFSRwqp1wK/Irud1jTR/w3IBPE9fpaqaY6X+wpnXJCw==,iv:xGVhgCJlnI7as9cqgpXUccm0AcfVe8MGZcfHtzEJSiY=,tag:x+AR96ExeXav0MFzqp2xHg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T20:42:00Z"
  mac: ENC[AES256_GCM,data:pDSVSvEDSukob6DSYeG2+AspGyY0FKbAA+L+f24BSS0F2zNliL+W3vHeNG3klTCzkF512nQd8iHaUYd3AvIN1MNrw33H4AJscnpsM+aOx/fPCCYBWJoQ4OJRkxgXQshZdGAd/irE4xZtkvun2iAC+Cw+/PkRUYH8ESAwdgbqBv0=,iv:u8zJERELPi138mpJFEo8FD85lNY92Xtf7azkaf2m2Us=,tag:b/Rogof/SdoH4mTZxnZy4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-backup-secret
type: Opaque
stringData:
  wasabi-id: ENC[AES256_GCM,data:8GFaGP305X3kXcD8O+EF8Z82Sco=,iv:UgW/5yc9XR9z5Cm3WPqPt8xuxbyFgHB0oYsbncmQSj8=,tag:mvqWNbTH7lD3kmApPUIEbQ==,type:str]
  wasabi-key: ENC[AES256_GCM,data:+Aowl8qnutY8RVSNb6ik36CcDAvx1Jmw+L9JYFhmZiUnVUv7kvLPsA==,iv:tU7C/WAX8xsgKXwXA4TyM31yym0vpa+C9gFIxJ7M13c=,tag:mY0+KSePPdfNShe78lV44g==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T20:42:00Z"
  mac: ENC[AES256_GCM,data:pDSVSvEDSukob6DSYeG2+AspGyY0FKbAA+L+f24BSS0F2zNliL+W3vHeNG3klTCzkF512nQd8iHaUYd3AvIN1MNrw33H4AJscnpsM+aOx/fPCCYBWJoQ4OJRkxgXQshZdGAd/irE4xZtkvun2iAC+Cw+/PkRUYH8ESAwdgbqBv0=,iv:u8zJERELPi138mpJFEo8FD85lNY92Xtf7azkaf2m2Us=,tag:b/Rogof/SdoH4mTZxnZy4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
