apiVersion: v1
kind: Secret
metadata:
  name: mariadb-cluster-secret
type: Opaque
stringData:
  mariadb-root-password: ENC[AES256_GCM,data:CvGNNyij42bg03wt+Mk1QTQLzMW1QtzNPSIkgNwq20RxFSRwqp1wK/Irud1jTR/w3IBPE9fpaqaY6X+wpnXJCw==,iv:xGVhgCJlnI7as9cqgpXUccm0AcfVe8MGZcfHtzEJSiY=,tag:x+AR96ExeXav0MFzqp2xHg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T20:53:27Z"
  mac: ENC[AES256_GCM,data:a/c3JsWr8lSEVy/HQn06Axj/cH/L03zIkww8gdu5QcM8d+i3es37vEf+zd/58JNDPCIoNVguMX9zbpaPmM6/6/ToIzgEah/ZExG6yy9Y0Ett/M6bvPvO4EzzXyO5Y5o9DS8DqYU9JrH9jBcz171x6AxJV2hioHOsLllDvUsJR7g=,iv:G0KcpzC18Guoc5x9/y6w2V9/2GexQ+IvPSLFvbuE5VI=,tag:7wX2lnXZJyy6dFWZScjAjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-user-secret
type: Opaque
stringData:
  wordpress-password: ENC[AES256_GCM,data:DQLNu8A+iq8ksDtUIGV9r71qZmvrO97EYSGj2Pyawh/yIpm55ZXLWrFFOy/9eqZNivGOAjAImC9x2sQdFM2vnw==,iv:Yf6kfV0s33LvWpMleSPD+PZj1QRw7xvPMUI6RwHkomw=,tag:w3dKxt8JcLGrr9Raty5Ixg==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T20:53:27Z"
  mac: ENC[AES256_GCM,data:a/c3JsWr8lSEVy/HQn06Axj/cH/L03zIkww8gdu5QcM8d+i3es37vEf+zd/58JNDPCIoNVguMX9zbpaPmM6/6/ToIzgEah/ZExG6yy9Y0Ett/M6bvPvO4EzzXyO5Y5o9DS8DqYU9JrH9jBcz171x6AxJV2hioHOsLllDvUsJR7g=,iv:G0KcpzC18Guoc5x9/y6w2V9/2GexQ+IvPSLFvbuE5VI=,tag:7wX2lnXZJyy6dFWZScjAjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-backup-secret
type: Opaque
stringData:
  wasabi-id: ENC[AES256_GCM,data:8GFaGP305X3kXcD8O+EF8Z82Sco=,iv:UgW/5yc9XR9z5Cm3WPqPt8xuxbyFgHB0oYsbncmQSj8=,tag:mvqWNbTH7lD3kmApPUIEbQ==,type:str]
  wasabi-key: ENC[AES256_GCM,data:+Aowl8qnutY8RVSNb6ik36CcDAvx1Jmw+L9JYFhmZiUnVUv7kvLPsA==,iv:tU7C/WAX8xsgKXwXA4TyM31yym0vpa+C9gFIxJ7M13c=,tag:mY0+KSePPdfNShe78lV44g==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbC9IcEZMMStnQkdBMEdl
        NmxveFA3Zys2RUtkSkkyaEVZNzZFenNuWmpzCmExQ09ZNEllcVludTg3VGRFOVNu
        RzY0ZzdtSmgyNWxvblBQZi91S2hEak0KLS0tIFdJME11MzNrOWRMS2dzM0EzVDNu
        Z2ZrdTFFVlpwYm1JVUwveUxDK3hqNFUK2Q4FACw9nPO8ruly9XyHLcETkvJbrrtk
        6/Q22vUEWfIbNgtszrmsLYfmuO540YtCCH8Uztek0ywYuRFsa0Lwtw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T20:53:27Z"
  mac: ENC[AES256_GCM,data:a/c3JsWr8lSEVy/HQn06Axj/cH/L03zIkww8gdu5QcM8d+i3es37vEf+zd/58JNDPCIoNVguMX9zbpaPmM6/6/ToIzgEah/ZExG6yy9Y0Ett/M6bvPvO4EzzXyO5Y5o9DS8DqYU9JrH9jBcz171x6AxJV2hioHOsLllDvUsJR7g=,iv:G0KcpzC18Guoc5x9/y6w2V9/2GexQ+IvPSLFvbuE5VI=,tag:7wX2lnXZJyy6dFWZScjAjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
