---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.mariadb.com/user_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: mariadb-operator
  passwordSecretKeyRef:
    name: mariadb-user-secret
    key: wordpress-password
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
