---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: user-apps-wordpress-httproute
  annotations:
    gatus.home-operations.com/endpoint: |-
      name: Wordpress
      group: external
spec:
  hostnames:
    - "mizu.to"
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: wordpress
          port: 80
#    - backendRefs:
#        - name: jellyfin-jellysearch
#          namespace: media
#          port: 5000
#      matches:
#        - queryParams:
#            - type: RegularExpression
#              name: "searchTerm"
#              value: "^.*$"
