apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  mariadb-password: ENC[AES256_GCM,data:JbqantQ1Vy98Lj/15KkbNHMHN5XQASIC1cClDQsHiA785GrBfc5vb7EvHKQcAyzJ3NUhNDOoo7RTVEEHj3tgng==,iv:u2IU0aiaDBrc8FvVZT6szDLCMqRs6iiHptt2i2eBlkM=,tag:2JNVNmHe0z/HtTvVeCoPAg==,type:str]
  wordpress-username: ENC[AES256_GCM,data:tDkbonzQJ8YERyFFHw==,iv:CBsb/tSQiIcuBYbHiZkDNy1I67aRxGfuEzxAxBlubYI=,tag:rQ09ouAEkcF4KcpbMkn3IA==,type:str]
  wordpress-password: ENC[AES256_GCM,data:ZZBtPwOCzjldZjSSrhBAgBRJn2tQujBK3olXIdd4JuIPgu5ZdETyig/8AGa8nxSzAZfQS+W67ehW2o7K/Fi0hA==,iv:OEuPhbTavZdgCd9WHuok9aP65c8XsCWtmMSj4ceFXH8=,tag:z4xpdCBicRj2Go9YCJH4eQ==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcGhEcmpTaDVtNXR0SmxT
        V1hwRzdCdWFkbW9TWTYzZ1Q0WnZrMVdXQW5BCndmVGVVUFMvNDdHYnJxTUI0UFBw
        S1NJd00raDVVdkZCMHNOemR3TTlsMlkKLS0tIDNtZk1yOFJaYjdtZlRuV29hWXZx
        TkZ1K0ZETjdwMUdXNkpzQ1BobkhKbFUKq1Jw5/pE7+iMMfd+0FGNQbJDACCs7qKi
        n58gryjXxc6DPdYqcGgQpFBwYCFQMR/nHrZAvdAcu2sX1RdjHY/Q7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-12T20:21:19Z"
  mac: ENC[AES256_GCM,data:sve4Gc2pYE7sKS1fv5WzfE0B23cskD2xYIEnJPglDoG/WDrroM+QrCwqejf0EYrusuOVwx8fl6w7yX4nPMUIc4orgZAF8ldXQ4mOeVSP5Wv8xSDH5LdUucyr4NJFjNyu+DQXyif2of1Tq8IDhteJmoeWM6aTPOZ2sAGQ9w/REWw=,iv:LOZAOO5pQSPapT97i4aAu3D19UxtfnTF4s9k4UxRl2A=,tag:HwCsIpdENVosxGCJiA4a8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
