apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  mariadb-password: ENC[AES256_GCM,data:JbqantQ1Vy98Lj/15KkbNHMHN5XQASIC1cClDQsHiA785GrBfc5vb7EvHKQcAyzJ3NUhNDOoo7RTVEEHj3tgng==,iv:u2IU0aiaDBrc8FvVZT6szDLCMqRs6iiHptt2i2eBlkM=,tag:2JNVNmHe0z/HtTvVeCoPAg==,type:str]
  wordpress-username: ENC[AES256_GCM,data:6eKnPtR2qGweh9HvpOjvd0xaN3g70mBLJ5K9CQR+FSuAzVQ87L6KBhq7O44aRrIMwoIHefmC9EXzClkdvLobRA==,iv:z9fbK3IH99Ovm7UMT4ghNlMqUAany/UiVlxJv6eTp+w=,tag:QJIyvKf4hK7116bkXDaQ9Q==,type:str]
  wordpress-password: ENC[AES256_GCM,data:ZZBtPwOCzjldZjSSrhBAgBRJn2tQujBK3olXIdd4JuIPgu5ZdETyig/8AGa8nxSzAZfQS+W67ehW2o7K/Fi0hA==,iv:OEuPhbTavZdgCd9WHuok9aP65c8XsCWtmMSj4ceFXH8=,tag:z4xpdCBicRj2Go9YCJH4eQ==,type:str]
sops:
  age:
    - recipient: age16rly7ap0jy4cmtkl0ylxly88jegwavlj3kdxh4ua8tfaduaw5p7qc4nafy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcGhEcmpTaDVtNXR0SmxT
        V1hwRzdCdWFkbW9TWTYzZ1Q0WnZrMVdXQW5BCndmVGVVUFMvNDdHYnJxTUI0UFBw
        S1NJd00raDVVdkZCMHNOemR3TTlsMlkKLS0tIDNtZk1yOFJaYjdtZlRuV29hWXZx
        TkZ1K0ZETjdwMUdXNkpzQ1BobkhKbFUKq1Jw5/pE7+iMMfd+0FGNQbJDACCs7qKi
        n58gryjXxc6DPdYqcGgQpFBwYCFQMR/nHrZAvdAcu2sX1RdjHY/Q7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T22:02:28Z"
  mac: ENC[AES256_GCM,data:lIsFRsA+ll19BalOuvD/DnBUQt3i72rT9g+nRxAZ9YVG6aTJ16757ZkAq8aQvmOtdt7noo1otapqvYrtQZcJFG6TmpYBSEPv+c9gO6TdEGTXic7X908rgkdTpewCa8/H0WmWxpJjWzBT2jHyY/rEtXIjE4K/QlYptrx9Nl0ry0Q=,iv:s3PWKDvQQABvJDCUPJQeG/tLPoHURji4qi7OIBOcBF8=,tag:pCkTCWJnf/PbnsQuEDR5rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
